Course.destroy_all
Course.create!(:name => 'Fresh Start! Raw Detox Diet', :owner_id => 1, :cost => 49700)
Course.create!(:name => 'Fresh Start! Energizing Diet', :owner_id => 1, :cost => 49700)
Course.create!(:name => '52 Indulgences', :owner_id => 1, :cost => 49700)
Course.create!(:name => 'Hatha Yoga', :owner_id => 1, :cost => 49700)
Course.create!(:name => 'The Lean Internet Business Certification System', :owner_id => 1, :cost => 49700)
Course.create!(:name => 'The Smarter Internet Marketer Tax Guide', :owner_id => 1, :cost => 49700)
Course.create!(:name => 'FB Shadow', :owner_id => 1, :cost => 49700)
Course.create!(:name => 'Webinar Lookin', :owner_id => 1, :cost => 49700)
Course.create!(:name => 'Get More Leads', :owner_id => 1, :cost => 49700)
Course.create!(:name => 'Ask Brittany', :owner_id => 1, :cost => 49700)
Course.create!(:name => 'The Smarter Internet Marketer Tax Guide Plus Bootcamp', :owner_id => 1, :cost => 49700)
Course.create!(:name => 'Never Ending Motivation', :owner_id => 1, :cost => 49700)
Course.create!(:name => 'Thin And Healthy Online', :owner_id => 1, :cost => 49700)
Course.create!(:name => '5 Pillars Of Success - Life Hacks That Help You Achieve Anything', :owner_id => 1, :cost => 49700)