WORKBOOK_COST_IN_CENTS = 295
IM_IDENTITY_MANAGER_TIME_OUT = 300 # 5 minutes

IM_ORDER_CREATED = 0
IM_ORDER_PAID = 1
IM_ORDER_REFUND = 2
IM_ORDER_COMPLIMENTARY = 3

IM_CONTENT_STATUS_DRAFT = 0
IM_CONTENT_STATUS_PUBLISH = 1

IM_BUSINESS_SALE_HOUSE_PERCENT_TAKE = 7.5 # 7.5%
IM_BUSINESS_SALE_HOUSE_PERCENT_TAKE_F = 0.075
IM_BUSINESS_SALE_HOUSE_BASE_TAKE = 100 # A dollar

IM_COURSE_PAYMENT_TYPE_ONE_TIME = 1
IM_COURSE_PAYMENT_TYPE_RECURRING = 2

IM_PAYLOAD_IMAGE = 1
IM_PAYLOAD_VIDEO = 2
IM_PAYLOAD_AUDIO = 3
IM_PAYLOAD_DOCUMENT = 4
IM_PAYLOAD_ARCHIVE = 5

IM_ARTICLE_PERMISSION_PUBLIC = 1
IM_ARTICLE_PERMISSION_PRIVATE = 2

IM_MARKET_SEGMENTATION_W_GOALS_WO_COURSES = 1
IM_MARKET_SEGMENTATION_W_COURSES_W_AFFILIATES = 2
IM_MARKET_SEGMENTATION_W_USER_FILTERING = 3


IM_MARKET_SENDGRID_STATUS_DRAFT = 0
IM_MARKET_SENDGRID_STATUS_SCHEDULED = 1
IM_MARKET_SENDGRID_STATUS_IN_PROGRESS = 2
IM_MARKET_SENDGRID_STATUS_SENT = 3

IM_TIMEZONE_SENDGRID = 'Pacific Time (US & Canada)'
IM_TIMEZONE_IDEALME = 'Eastern Time (US & Canada)'

IM_DISPLAY_TYPE_NORMAL = 1
IM_DISPLAY_TYPE_FEATURE = 2

IM_APP_WALL = 1
IM_APP_PROGRESS_WATCH = 2
IM_APP_FOLLOW = 3
IM_APP_WATCH = 4

IM_ACTIVITY_TYPE_NOTIFICATION = 1
IM_ACTIVITY_TYPE_FEED = 2

IM_PROGRESS_WATCH_MAX = 5
IM_PROGRESS_WATCH_YES = IM_PROGRESS_WATCH_MAX
IM_PROGRESS_WATCH_NO = 1
IM_PROGRESS_WATCH_MISSED = 0

IM_SURVEY_QUESTION_TYPE_RADIO = 1
IM_SURVEY_QUESTION_TYPE_SELECT = 2
IM_SURVEY_QUESTION_TYPE_TEXT = 3

IM_SCRUBBER_SELF_EXCEPTION_UNKNOWN_P_TYPE = 1
IM_SCRUBBER_DB_EXCEPTION_MISSING_F_OBJECT = 1
IM_SCRUBBER_DB_EXCEPTION_NOT_NULLABLE = 2

IM_HOSTNAME = `hostname`.strip

IM_S3_URL_TTL = 120