
HIPCHAT_AUTH_TOKEN: 2876c736673caf9c04fd310cdb2e47

development:
  AWS_ACCESS_KEY_ID: AKIAJLDIGUPMHU2FYWPA
  AWS_S3_BUCKET: idealme-dev
  AWS_SECRET_ACCESS_KEY: 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

  AWS_CF_KEY_PAIR_ID: APKAJS4Y4PIVZFGAJ3YQ

  STRIPE_PUBLISHABLE_KEY: pk_test_UFxGLAylGvWNmaJjFPpQrjvW
  STRIPE_SECRET_KEY: sk_test_McolaUo3frJYYalxTTjg0Au1
  FACEBOOK_API_KEY: 472752126173830
  FACEBOOK_API_SECRET: 74b000941594ca5c509acac04c557cc9

  BRITTANY_PAYPAL_ENDPOINT: api.sandbox.paypal.com
  BRITTANY_PAYPAL_AUTH_KEY: AbZSqxC6PpbEU7aO_ciSwYBlq2w9M4-6Kd9u7sJeGE9zCx6QWX8Tvr8ks90S
  BRITTANY_PAYPAL_AUTH_SECRET: EISO4xAsSekjS86Mx4gXinxzPwIV671J8ylxBeTW2xStgvbsv4hSu0y6Plfo

  IDEALME_PAYPAL_ENDPOINT: https://api.sandbox.paypal.com
  IDEALME_PAYPAL_AUTH_KEY: AcaG_RCBUAghLr5wSENJK0m5pz1Cx6q_aXLfb3y8Zbt84nFav0JiB0BfeRX4
  IDEALME_PAYPAL_AUTH_SECRET: EJi7LxAUkeRT93IFs7sJGi5P_-nthESjLn-R5y_qytTUaDxNkV3VhFqGQRLn

  SENDGRID_API_PASSWORD: ralphy28E!
  SENDGRID_API_USERNAME: idealme

test:
  AWS_CF_KEY_PAIR_ID: APKAJS4Y4PIVZFGAJ3YQ
  STRIPE_PUBLISHABLE_KEY: pk_test_UFxGLAylGvWNmaJjFPpQrjvW
  STRIPE_SECRET_KEY: sk_test_McolaUo3frJYYalxTTjg0Au1
  FACEBOOK_API_KEY: 472752126173830
  FACEBOOK_API_SECRET: 74b000941594ca5c509acac04c557cc9

  BRITTANY_PAYPAL_ENDPOINT: api.sandbox.paypal.com
  BRITTANY_PAYPAL_AUTH_KEY: AbZSqxC6PpbEU7aO_ciSwYBlq2w9M4-6Kd9u7sJeGE9zCx6QWX8Tvr8ks90S
  BRITTANY_PAYPAL_AUTH_SECRET: EISO4xAsSekjS86Mx4gXinxzPwIV671J8ylxBeTW2xStgvbsv4hSu0y6Plfo

  IDEALME_PAYPAL_ENDPOINT: https://api.sandbox.paypal.com
  IDEALME_PAYPAL_AUTH_KEY: AcaG_RCBUAghLr5wSENJK0m5pz1Cx6q_aXLfb3y8Zbt84nFav0JiB0BfeRX4
  IDEALME_PAYPAL_AUTH_SECRET: EJi7LxAUkeRT93IFs7sJGi5P_-nthESjLn-R5y_qytTUaDxNkV3VhFqGQRLn

  SENDGRID_API_PASSWORD: ralphy28E!
  SENDGRID_API_USERNAME: idealme

staging:
  STRIPE_PUBLISHABLE_KEY: pk_test_UFxGLAylGvWNmaJjFPpQrjvW
  STRIPE_SECRET_KEY: sk_test_McolaUo3frJYYalxTTjg0Au1
  FACEBOOK_API_KEY: 472752126173830
  FACEBOOK_API_SECRET: 74b000941594ca5c509acac04c557cc9

  BRITTANY_PAYPAL_ENDPOINT: api.sandbox.paypal.com
  BRITTANY_PAYPAL_AUTH_KEY: AbZSqxC6PpbEU7aO_ciSwYBlq2w9M4-6Kd9u7sJeGE9zCx6QWX8Tvr8ks90S
  BRITTANY_PAYPAL_AUTH_SECRET: EISO4xAsSekjS86Mx4gXinxzPwIV671J8ylxBeTW2xStgvbsv4hSu0y6Plfo

  IDEALME_PAYPAL_ENDPOINT: https://api.sandbox.paypal.com
  IDEALME_PAYPAL_AUTH_KEY: AcaG_RCBUAghLr5wSENJK0m5pz1Cx6q_aXLfb3y8Zbt84nFav0JiB0BfeRX4
  IDEALME_PAYPAL_AUTH_SECRET: EJi7LxAUkeRT93IFs7sJGi5P_-nthESjLn-R5y_qytTUaDxNkV3VhFqGQRLn

  SENDGRID_API_PASSWORD: ralphy28E!
  SENDGRID_API_USERNAME: idealme

production:
  AWS_ACCESS_KEY_ID: AKIAJLDIGUPMHU2FYWPA
  AWS_CF_KEY_PAIR_ID: APKAIS27M4HGDLWDGQAQ
  AWS_S3_BUCKET: idealme-prod
  AWS_SECRET_ACCESS_KEY: ie2hC2I3cD9D0ZOEneNebh7C2Rqb88S0PWuTtTR8


  AUTHORIZED_NET_LOGIN: 5zKG6HaL25f4
  AUTHORIZED_NET_PASSWORD: 2eMsq3rD3kH266Nc
  FACEBOOK_API_KEY: 472752126173830
  FACEBOOK_API_SECRET: 74b000941594ca5c509acac04c557cc9


  BRITTANY_PAYPAL_ENDPOINT: api.paypal.com
  BRITTANY_PAYPAL_AUTH_KEY: ARtP5BBTK7ApCrGznOa2ZtewXgGceZBA-bv6e5fEqt7ZoKEQpkRFkgpU4Yn9
  BRITTANY_PAYPAL_AUTH_SECRET: EDKNMhBHAZ9DoUHdGW5FzB_YHC_DNs7CtteHr_ensTIgyynDh2LG7UpSmbyJ

  IDEALME_PAYPAL_ENDPOINT: https://api.paypal.com
  IDEALME_PAYPAL_AUTH_KEY: AaW_BhC_cGxYnMJoyH5ZYKHwTEDNDoEcpzr5kWsAjxAx6peMC-Fg2vKUlC0P
  IDEALME_PAYPAL_AUTH_SECRET: EBsv5xB3Gzp34dqv0rMDyhmrLwWoDB4eJjMO8RhF2OlAN0nGzL1XFABvMfMt

  SENDGRID_API_PASSWORD: ralphy28E!
  SENDGRID_API_USERNAME: idealme
  STRIPE_PUBLISHABLE_KEY: pk_live_3U5jcgOq5rJhWOQ9sk36ICRP
  STRIPE_SECRET_KEY: sk_live_H85LVuLxRStwzSfTlZbNtfJC
  TWITTER_CONSUMER_KEY: 1JH2sJRWw4AnL8PTZevlEQ
  TWITTER_CONSUMER_SECRET: jLgQVsN5dDPltn2o9IvquvDwo4Q9baWWM2Pa7s4KTw
