defaults: &defaults
  pool: 10
  adapter: postgresql
  host: localhost
  port: 5432 # connect directly to postgres
  timeout: 5000
  database: idealme_development
  username: idealme
  password: secret

development:
  <<: *defaults

test:
  <<: *defaults
  database: idealme_test

