defaults: &defaults
  pool: 5
  adapter: postgresql
  host: localhost
  port: 5432 # connect directly to postgres
  timeout: 5000
  database: idealme_development
  username: idealme
  password:

development:
  <<: *defaults


test:
  <<: *defaults
  database: idealme_test

staging:
  <<: *defaults
  username: idealme_rw
  password: 32e982h3e92h!
  database: idealme_staging

production:
  <<: *defaults
  database: idealme_production

