DEFAULTS: &defaults
  adapter: mysql2
  host: 127.0.0.1
  encoding: utf8
  username: root
  password:

development:
  <<: *defaults
  database: idealme_dev

test:
  <<: *defaults
  database: idealme_test<%= ENV['TEST_ENV_NUMBER'] %>

staging:
  <<: *defaults     
  username: idealme_rw
  password: 32e982h3e92h!
  database: idealme_staging

production:
  <<: *defaults
  database: idealme_prod

