defaults: &defaults
  pool: 5
  adapter: postgresql
  host: localhost
  port: 5432 # connect directly to postgres
  timeout: 5000
  database: idealme_development
  username: idealme
  password:

development:
  <<: *defaults

test:
  <<: *defaults
  database: idealme_test

staging:
  <<: *defaults
  database: idealme_staging
  password: UjUyfCBZh89Wqd


production:
  <<: *defaults
  database: idealme_production
  password: UjUyfCBZh89Wqd

