development:
  access_key_id: AKIAJLDIGUPMHU2FYWPA
  secret_access_key: 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
test:
  access_key_id: AKIAJLDIGUPMHU2FYWPA
  secret_access_key: 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
production:
  access_key_id: AKIAJLDIGUPMHU2FYWPA
  secret_access_key: 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
staging:
  access_key_id: AKIAJLDIGUPMHU2FYWPA
  secret_access_key: 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
  