skin : o2k7
skin_variant : silver
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - fullscreen
plugins:
  - table
  - fullscreen
  - fullscreen
theme_advanced_resizing: true
fullscreen_new_window: true
fullscreen_settings:
  theme_advanced_path_location: top