---
- hosts: all
  user: vagrant
  remote_user: vagrant
  vars_files:
    - vars/defaults.yml

  roles:
    - common
    - curl
    # - deploy-user
    # - ssh
    # - ruby-1.9.3
    - ruby-2.0.0
    - database
    # - common
    # - webserver
    # - sidekiq

  tasks:
  - name: Run bundle install
    shell: 'cd /vagrant && bundle install'

